version: "3.5"

services:
  postgres:
    image: postgres:15beta2-alpine
    restart: unless-stopped
    environment:
      PGDATA: /data/postgres
    env_file:
      - .env
    volumes:
      - ./docker/postgres/data:/data/postgres
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
